tasks:
  - name: Database
    init: docker pull postgres:14-alpine
    command: docker run -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=p0stgr3s postgres:14-alpine

  - name: dev
    init: |
      nvm i 18
      nvm use 18
      pnpm i
      pnpm prepack
      cd packages/core
      pnpm build
      cd -
      pnpm connectors build
      pnpm cli connector link
    command: |
      gp ports await 5432
      sleep 3
      export ENDPOINT=$(gp url 3001)
      export ADMIN_ENDPOINT=$(gp url 3002)
      pnpm cli db seed
      pnpm start:dev
    env:
      TRUST_PROXY_HEADER: 1
      DB_URL: postgres://postgres:p0stgr3s@127.0.0.1:5432/dib

ports:
  - name: dib
    port: 3001
    visibility: public
  - name: Admin Console
    port: 3002
    visibility: public
  - name: Postgres
    port: 5432
    visibility: public
    onOpen: ignore
  - port: 5001
    onOpen: ignore